const branchData={bandung:{name:"Bandung",wa:"6285196049990",waDisplay:"0851-9604-9990",tel:"085196049990",telDisplay:"0851-9604-9990",address:"Rumah Khitan Kak Topa, Jl. Raya Ujung Berung No.230, Cipadung Kulon, Panyileukan, Bandung City, West Java 40614",gmapsLink:"https://maps.app.goo.gl/Z95mLaeuD8NTp4sYA",gmapsIframe:"https://maps.google.com/maps?q=Rumah%20Khitan%20Kak%20Topa%2C%20Jl.%20Raya%20Ujung%20Berung%20No.230%2C%20Cipadung%20Kulon%2C%20Panyileukan%2C%20Bandung%20City%2C%20West%20Java%2040614&t=&z=15&ie=UTF8&iwloc=&output=embed",prices:{bronze:"Rp 1.500.000",gold:"Rp 2.000.000",platinum:"Rp 2.500.000",vip:"Rp 3.500.000",dewasa:"Rp 4.000.000"}},garut:{name:"Garut",wa:"6281220224867",waDisplay:"0812-2022-4867",tel:"081220224867",telDisplay:"0812-2022-4867",address:"Rumah Khitan Kak Topa, Jl. Bratayuda No.38, Regol, Garut Kota, Garut Regency, West Java 44114",gmapsLink:"https://maps.app.goo.gl/DoZAuNwAERd8Hqgv6",gmapsIframe:"https://maps.google.com/maps?q=Rumah%20Khitan%20Kak%20Topa%2C%20Jl.%20Bratayuda%20No.38%2C%20Regol%2C%20Garut%20Kota%2C%20Garut%20Regency%2C%20West%20Java%2044114&t=&z=15&ie=UTF8&iwloc=&output=embed",prices:{bronze:"Rp 1.500.000",gold:"Rp 2.000.000",platinum:"Rp 2.500.000",vip:"Rp 3.500.000",dewasa:"Rp 4.000.000"}}};let currentBranch='bandung';window.openBranchModal=function(){const modal=document.getElementById('branchModal');if(modal){modal.classList.add('active');document.body.style.overflow='hidden';const closeBtn=document.getElementById('modalCloseBtn');if(localStorage.getItem('rkTopaBranch')&&closeBtn){closeBtn.style.display='block'}}};window.closeBranchModal=function(){const modal=document.getElementById('branchModal');if(modal){modal.classList.remove('active');document.body.style.overflow=''}};window.setGlobalBranch=function(branchKey){if(branchData[branchKey]){currentBranch=branchKey;localStorage.setItem('rkTopaBranch',branchKey);updateDOMData();closeBranchModal()}};function updateDOMData(){const data=branchData[currentBranch];if(!data)return;document.querySelectorAll('.current-branch-text').forEach(el=>el.textContent=data.name);const activeLabel=document.getElementById('active-branch-label');if(activeLabel)activeLabel.textContent=`📍 Cabang ${data.name}`;document.querySelectorAll('a[data-link="wa"]').forEach(el=>{el.href='javascript:void(0)';el.onclick=window.openContactModal});document.querySelectorAll('span[data-price]').forEach(el=>{const pkg=el.getAttribute('data-price');if(data.prices[pkg]){el.textContent=data.prices[pkg]}})}
document.addEventListener('DOMContentLoaded',()=>{renderUniversalContacts();const savedBranch=localStorage.getItem('rkTopaBranch');if(savedBranch&&branchData[savedBranch]){currentBranch=savedBranch;updateDOMData()}else{setTimeout(()=>{openBranchModal()},500);updateDOMData()}});const faqQuestions=document.querySelectorAll('.faq-question');faqQuestions.forEach(question=>{question.addEventListener('click',()=>{const item=question.parentElement;const answer=question.nextElementSibling;document.querySelectorAll('.faq-item').forEach(otherItem=>{if(otherItem!==item&&otherItem.classList.contains('active')){otherItem.classList.remove('active');otherItem.querySelector('.faq-answer').style.maxHeight=null}});item.classList.toggle('active');if(item.classList.contains('active')){answer.style.maxHeight=answer.scrollHeight+"px"}else{answer.style.maxHeight=null}})});const hamburger=document.getElementById('hamburger');const navMenu=document.getElementById('nav-menu');if(hamburger&&navMenu){hamburger.addEventListener('click',()=>{navMenu.classList.toggle('active')});const navLinksMobile=navMenu.querySelectorAll('.nav-link');navLinksMobile.forEach(link=>{link.addEventListener('click',()=>{navMenu.classList.remove('active')})})}
const sections=document.querySelectorAll('section[id]');const navLinks=document.querySelectorAll('.nav-link');window.addEventListener('scroll',()=>{let current='';sections.forEach(section=>{const sectionTop=section.offsetTop;if(pageYOffset>=(sectionTop-120)){current=section.getAttribute('id')}});navLinks.forEach(link=>{link.classList.remove('active');if(link.getAttribute('href')===`#${current}`){link.classList.add('active')}})});document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){const targetId=this.getAttribute('href');if(targetId==='#')return;const targetElement=document.querySelector(targetId);if(targetElement){e.preventDefault();const navbarHeight=80;const targetPosition=targetElement.getBoundingClientRect().top+window.pageYOffset-navbarHeight;window.scrollTo({top:targetPosition,behavior:'smooth'})}})});window.openBookingModal=function(paket=''){const modal=document.getElementById('bookingModal');if(modal){modal.classList.add('active');document.body.style.overflow='hidden';const branchSelect=document.getElementById('book-branch');if(branchSelect){branchSelect.value=currentBranch}
const packageSelect=document.getElementById('book-package');if(packageSelect){packageSelect.value=paket}}};window.closeBookingModal=function(){const modal=document.getElementById('bookingModal');if(modal){modal.classList.remove('active');document.body.style.overflow=''}};window.submitBooking=function(event){event.preventDefault();const branchId=document.getElementById('book-branch').value;const paket=document.getElementById('book-package').value;const name=document.getElementById('book-name').value;const age=document.getElementById('book-age').value;const parent=document.getElementById('book-parent').value;const branchInfo=branchData[branchId];let text=`Halo Rumah Khitan Kak Topa Cabang ${branchInfo.name},\n`;text+=`Saya ingin mendaftar dengan detail berikut:\n\n`;text+=`- Nama Pasien: ${name}\n`;text+=`- Usia: ${age}\n`;if(parent){text+=`- Nama Orang Tua: ${parent}\n`}
text+=`- Paket Pilihan: ${paket}\n\n`;text+=`Mohon informasi lebih lanjut. Terima kasih.`;const encodedText=encodeURIComponent(text);const waUrl=`https://wa.me/${branchInfo.wa}?text=${encodedText}`;window.open(waUrl,'_blank');closeBookingModal()};window.openContactModal=function(e){if(e)e.preventDefault();const modal=document.getElementById('contactModal');if(modal){modal.classList.add('active');document.body.style.overflow='hidden'}};window.closeContactModal=function(){const modal=document.getElementById('contactModal');if(modal){modal.classList.remove('active');document.body.style.overflow=''}};window.directContact=function(branchId){const branchInfo=branchData[branchId];if(branchInfo){const text=`Halo Rumah Khitan Kak Topa Cabang ${branchInfo.name}, saya ingin konsultasi.`;const encodedText=encodeURIComponent(text);const waUrl=`https://wa.me/${branchInfo.wa}?text=${encodedText}`;window.open(waUrl,'_blank');closeContactModal()}};function renderUniversalContacts(){const container=document.getElementById('universal-contact-container');if(!container)return;let html='';for(const key in branchData){const branch=branchData[key];html+=`
      <div class="universal-contact-card">
        <div class="universal-contact-header">
          <h3>📍 Cabang ${branch.name}</h3>
        </div>
        <div class="universal-contact-map">
          <iframe src="${branch.gmapsIframe}" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
        <div class="universal-contact-body">
          <div class="contact-item" style="margin-bottom: 0;">
            <div class="contact-icon">📍</div>
            <div class="contact-detail">
              <p style="margin: 0; color: var(--text); font-size: 0.95rem; line-height: 1.5;">${branch.address}</p>
              <a href="${branch.gmapsLink}" target="_blank" style="color: var(--primary); font-weight: 500; font-size: 0.9rem; display: inline-block; margin-top: 4px;">Buka di Google Maps →</a>
            </div>
          </div>
          
          <div class="contact-item" style="margin-bottom: 0;">
            <div class="contact-icon">📞</div>
            <div class="contact-detail">
              <a href="tel:${branch.tel}" style="font-size: 1.1rem; font-weight: 600; color: var(--text); text-decoration: none;">${branch.telDisplay}</a>
              <p style="font-size: 0.85rem; color: var(--secondary-text); margin: 0;">Panggilan Suara Langsung</p>
            </div>
          </div>
          
          <button onclick="directContact('${key}')" class="btn btn-primary btn-block" style="display: flex; justify-content: center; align-items: center; gap: 8px;">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
            Chat WhatsApp
          </button>
        </div>
      </div>
    `}
container.innerHTML=html}